server:
  port: 10010
spring:
  application:
    name: changyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取服务的间隔时间
zuul:
  prefix: /api #前缀
  routes:
    item-service: /item/** #路由到商品的微服务